apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: event-schema
  name: kubeslice-controller-event-schema-conf
  namespace: kubeslice-controller
data:
  controller.yaml: |-
    disabledEvents:
      - ProjectDeleted
      - ProjectDeletionFailed
      - ClusterInstallationInProgress
      - ClusterInstallationFailed
      - ClusterInstallationPending
      - ClusterDeleted
      - ClusterDeletionFailed
      - ClusterDeregistrationInProgress
      - ClusterDeregistered
      - ClusterDeregisterTimeout
      - ClusterDeregisterFailed
      - SliceConfigDeleted
      - SliceConfigDeletionFailed
      - ServiceExportConfigDeleted
      - ServiceExportConfigDeletionFailed
      - DefaultSliceQoSConfigCreated
      - SliceQoSConfigDeleted
      - SliceQoSConfigDeletionFailed
      - SecretDeleted
      - SecretDeletionFailed
      - NamespaceCreated
      - NamespaceCreationFailed
      - NamespaceDeleted
      - NamespaceDeletionFailed
      - WorkerClusterRoleCreated
      - WorkerClusterRoleCreationFailed
      - WorkerClusterRoleUpdated
      - WorkerClusterRoleUpdateFailed
      - ReadOnlyRoleCreated
      - ReadOnlyRoleCreationFailed
      - ReadOnlyRoleUpdated
      - ReadOnlyRoleUpdateFailed
      - ReadWriteRoleCreated
      - ReadWriteRoleCreationFailed
      - ReadWriteRoleUpdated
      - ReadWriteRoleUpdateFailed
      - ServiceAccountCreated
      - ServiceAccountCreationFailed
      - ServiceAccountSecretCreated
      - ServiceAccountSecretCreationFailed
      - DefaultRoleBindingCreated
      - DefaultRoleBindingCreationFailed
      - DefaultRoleBindingUpdated
      - DefaultRoleBindingUpdateFailed
      - DefaultRoleBindingDeleted
      - DefaultRoleBindingDeletionFailed
      - InactiveRoleBindingDeleted
      - InactiveRoleBindingDeletionFailed
      - InactiveServiceAccountDeleted
      - InactiveServiceAccountDeletionFailed
      - ServiceAccountDeleted
      - ServiceAccountDeletionFailed
      - WorkerServiceImportDeletedForcefully
      - WorkerServiceImportRecreationFailed
      - WorkerServiceImportRecreated
      - WorkerServiceImportCreationFailed
      - WorkerServiceImportCreated
      - WorkerServiceImportUpdateFailed
      - WorkerServiceImportUpdated
      - WorkerServiceImportDeleted
      - WorkerServiceImportDeletionFailed
      - WorkerSliceConfigDeletedForcefully
      - WorkerSliceConfigRecreationFailed
      - WorkerSliceConfigRecreated
      - WorkerSliceConfigCreationFailed
      - WorkerSliceConfigCreated
      - WorkerSliceConfigUpdateFailed
      - WorkerSliceConfigUpdated
      - WorkerSliceConfigDeleted
      - WorkerSliceConfigDeletionFailed
      - WorkerSliceGatewayDeletedForcefully
      - WorkerSliceGatewayRecreationFailed
      - WorkerSliceGatewayRecreated
      - WorkerSliceGatewayDeletionFailed
      - WorkerSliceGatewayDeleted
      - WorkerSliceGatewayCreationFailed
      - WorkerSliceGatewayCreated
      - SliceGatewayJobCreationFailed
      - SliceGatewayJobCreated
      - VPNKeyRotationConfigCreated
      - VPNKeyRotationConfigCreationFailed
      - VPNKeyRotationStart
      - VPNKeyRotationConfigUpdated
      - CertificateJobCreationFailed
      - CertificatesRenewNow
      - IllegalVPNKeyRotationConfigDelete
      - CertificateJobFailed
