apiVersion: controller.kubeslice.io/v1alpha1
kind: SliceConfig
metadata:
  name: demo-hub-spoke
  namespace: kubeslice-avesha
spec:
  sliceSubnet: "10.1.0.0/16"
  clusters: ["hub", "spoke1", "spoke2", "spoke3"]
  topologyConfig:
    topologyType: hub-spoke
    hubSpoke:
      hubClusters: ["hub"]
      spokeClusters: ["spoke1", "spoke2", "spoke3"]
      allowSpokeToSpoke: false
    clusterRoles:
      - clusterName: hub
        vpnRole: server
      - clusterName: spoke1
        vpnRole: client
      - clusterName: spoke2
        vpnRole: client
      - clusterName: spoke3
        vpnRole: client